### ISSUE TITLE
发送结束游戏会直接开启下一把

### ISSUE THREAD

**Issue by MTmin** [MeetWq/nonebot-plugin-handle#1]
发送结束游戏会直接开启下一把
![image](https://user-images.githubusercontent.com/32099406/161388365-8ddec84a-9a6f-4b86-8fa1-133a3d3bfffd.png)

**Comment by MeetWq** [comment]
我也不知道为什么会这样
这种情况常见吗

**Comment by MTmin** [comment]
> 我也不知道为什么会这样这种情况很 常见吗

一直出....没不出的情况

**Comment by MeetWq** [comment]
fix in d5574499b40b31649e4ae5cf0b6c4b3f97caa0cd
